### ISSUE TITLE
onProviderDisabled/Enabled is not working properly

### ISSUE THREAD

**Issue by Larnoo** [mapzen/lost#123]
- When gps provider status changed, the onProviderDisabled/Enabled is working properly.
- But when network provider  status changed, the onProviderDisabled/Enabled is not working properly。
- (I close wifi , mobile data, change to airplane mode.  the onProviderDisabled/Enabled is not work.)

**Comment by ecgreb** [comment]
We are looking into this. Initial testing seems to indicate the callbacks are triggered when a provider is disabled using the location system settings (toggling mode between high accuracy, battery saving, and device only) but not when enabled.

Also please be aware that `LocationListener.onProviderDisabled()` and `LocationListener.onProviderDisabled()` will soon be deprecated in favor of `LocationAvailability`.

**Comment by ecgreb** [comment]
So it turns out these methods are actually working as expected [according to the Android docs](https://developer.android.com/reference/android/location/LocationListener.html).

> These methods are called if the LocationListener has been registered with the location manager service using the requestLocationUpdates(String, long, float, LocationListener) method.

Lost registers its listeners with the `LocationManager` selectively [based on the priority](https://github.com/mapzen/lost/blob/master/lost/src/main/java/com/mapzen/android/lost/api/LocationRequest.java#L61) set when creating a location request.

For example if the priority is `PRIORITY_BALANCED_POWER_ACCURACY` then no listener will be set on the GPS provider and enabled/disabled callbacks will not be invoked for it. However callbacks will still be invoked for the network provider.

Documentation and demo app have been updated here https://github.com/mapzen/lost/pull/137.
