### ISSUE TITLE
gps required

### ISSUE THREAD

**Issue by cjkiller** [mapzen/lost#169]
Just built a map app using mapbox which uses this library. The app is built for android wear which often don't have gps sensors, this library uses:

<uses-feature android:name="android.hardware.location.gps"/>

Which adds required = true (as its not specified) when merging manifests. Searching the library it shows gpsPresent boolean so I'm guessing gps required could be set to false.

<uses-feature android:name="android.hardware.location.gps"  android:required="false"/>

Hopefully its an easy change

Craig

**Comment by ecgreb** [comment]
Good catch!

I agree the correct solution here would be to use `android:required="false"` for the GPS feature.

Does Android wear typically have _any_ location sensors or does it rely on the paired device?

If so should we consider making `android.hardware.location` also not required? Also perhaps `android.hardware.wifi` should be replaced by `android.hardware.location.network`?

**Comment by cjkiller** [comment]
Just done a quick search in the dev console with another app, it has android.hardware.location as a feature, non gps watches are showing up as supported. I guess wifi or bluetooth most set this to be compatible but have no real idea. So i'm guessing nearly all devices will support android.hardware.location.

**Comment by Guardiola31337** [comment]
The same thing happens with WiFi.

In order to get it running with Google SDK and skip the problem mentioned by @cjkiller, we had to add `tools:node="remove"` in wear's [`Manifest.xml`](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidWearDemo/src/main/AndroidManifest.xml#L12) in all `uses-feature` which were causing conflict.
Although we run into the [same issue](https://github.com/mapbox/mapbox-gl-native/issues/8506#issue-216380264) when using Lost.

Don't know follow implications because there are watches with and without GPS and Google's library does the wiring automatically so when you have a watch without GPS paired with a mobile you still receive updates using same APIs.
You can see that there is [nothing special in the code](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidWearDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/GoogleLocationEngine.java) and was tested in a watch without GPS.

![trackinglocationwear](https://cloud.githubusercontent.com/assets/1668582/24287524/5da71eaa-107a-11e7-8198-a8b836399d21.gif)

It'd be awesome to have same functionality in Lost. Are you planning to support it?
Thanks @ecgreb
