### ISSUE TITLE
Unable to register for network updates

### ISSUE THREAD

**Issue by stepanmazokha** [mapzen/LOST#29]
When I try to implement LOST library, I receive this exception: (I am using Genymotion emulator for Android API 21, GPS is turned on and the example app is working properly)

'
FusionEngine﹕ Unable to register for network updates.
java.lang.IllegalArgumentException: provider doesn't exist: network
'

This exception can be seen, when calling 'LocationServices.FusedLocationApi.requestLocationUpdates(locationRequest, mLocationListener);'

Of course, before this I run 'mLOSTClient = new LostApiClient.Builder(mContext).build();' and then 'mLOSTClient.connect();'. and listener is also initialized. 

What should I do?

**Comment by ecgreb** [comment]
Its failing to connect because Genymotion does not have a network location provider. This exception is handled by LOST and the app should still function normally (minus network location updates).

You can still test location updates using Genymotion's GPS simulator if you enable `PRIORITY_HIGH_ACCURACY` for your location update requests.

**Comment by stepanmazokha** [comment]
@ecgreb thank you for the reply!
