### ISSUE TITLE
Make .gpx speed list optional

### ISSUE THREAD

**Issue by miniyou** [mapzen/LOST#45]
Currently, `NodeList speedList` is mandatory or the app will crash while mocking the file. It should be a trivial modification to make it optional.

Most tracks available on openstreetmap lack speed tags, and the current workaround is to append a large number of `<speed>0</speed>` to the track segment.

Possibly related: it would be nice to make a gpx extension allowing accuracy, since this might be important while testing an app. Also see #37.

**Comment by ecgreb** [comment]
This is a great suggestion and is definitely on our radar. Also would be nice to include some other input validation for trace files so the app does not crash due to any invalid data of any sort.

We will add this to the list of things to work on for the next version. Feel free to submit a PR if you need this feature sooner.
