### ISSUE TITLE
Manage multiple location listeners in FusedLocationProviderApi

### ISSUE THREAD

**Issue by dmeignan** [mapzen/LOST#47]
Currently, only one LocationListener can be register at a given time in the implementation of the `FusedLocationProviderApi` (the [FusedLocationProviderApiImpl](https://github.com/mapzen/LOST/blob/master/lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java)). It would be nice to have a list of listeners.

The reason: I currently develop an application with Mapbox, which use the `FusedLocationProviderApi`, but I also have another component that requires listening to location updates (using the LOST API). If my other component sends a request for location updates, the Mapbox component will not receive any more location updates because there is only one `LocationListener` in `FusedLocationProviderApiImpl` (and also because the `FusedLocationProviderApi` is static, which seems normal).

This modification would require a bit of coding to "combine" the [requests](https://github.com/mapzen/LOST/blob/master/lost/src/main/java/com/mapzen/android/lost/api/LocationRequest.java). For instance, if a request asks for a `PRIORITY_HIGH_ACCURACY` and another for `PRIORITY_LOW_POWER`, then the `PRIORITY_HIGH_ACCURACY` will be the effective priority. Same for the updates intervals and displacement.

**Comment by msmollin** [comment]
@dmeignan thanks for the request! 

A couple thoughts for discussion:
- While I agree the accuracy request and displacement makes sense that `PRIORITY_HIGH_ACCURACY` should always supercede `PRIORITY_LOW_POWER`, I'm not so sure on the update intervals. Its entirely conceivable that location updates will trigger logic that has performance impacting implications, so increasing that update interval across the board may have negative side effects.

- Adding onto that, it may be difficult to just discard the original subscription as really what would be ideal is the following (and much more involved): 
1) Subscriber A subscribes at `PRIORITY_LOW_POWER`
2) Subscriber B subscribes at `PRIORITY_HIGH_ACCURACY`, and so Subscriber A now receives the same accuracy
3) Subscriber B unsubscribes. Subscriber A now goes back to receiving `PRIORITY_LOW_POWER`

- I'm wondering if the core problem couldn't be solved by using something like Square's Otto (http://square.github.io/otto/), since that's effectively what we'd have to implement here to be able to track multiple listeners and subscriptions. Granted, it wouldn't solve the request precedence problem, but it would handle multiple listeners. 

Thoughts?

**Comment by ecgreb** [comment]
If this is within the context of a single application multiple listeners should not be required. Location updates can be shared via broadcast intents or an event bus (as @msmollin suggests) or some other means.

**Comment by dmeignan** [comment]
On using broadcast intents or event bus:

- The use of broadcast intents is indeed a nice idea. However, it does not really solve the problem of having different components that request different location updates (different accuracies and intervals). If a first component makes a location update request, when a second component makes another request it will overwrite the first one. It was the initial problem I came across: One library I use, overwrites the location request send by another component of my app. To solve this problem, I have to synchronize/coordinate the requests, which leads to the next point:

Should I consider the LOST `LocationServices` as Services (which manage multiple clients/subscribers) or should I encapsulate each LocationService in a class that coordinates the requests?

- The Google [FusedLocationProviderApi](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderApi) is designed as a service that can manage multiple subscribers. If the LOST API have another approach, the name of some methods and classes may be misleading. E.g. The method `removeLocationUpdates(LocationListener listener);` in [FusedLocationProviderApi](https://github.com/mapzen/LOST/blob/master/lost/src/main/java/com/mapzen/android/lost/api/FusedLocationProviderApi.java) should be something like `stopLocationUpdates()` with no `listener` parameter (because it is not used in its [implementation](https://github.com/mapzen/LOST/blob/master/lost/src/main/java/com/mapzen/android/lost/internal/FusedLocationProviderApiImpl.java)).

Concerning the combination of request parameters:

- Indeed, (as @msmollin pointed out) using the smallest update interval among the registered requests can have some impacts on the logic of the location listeners/subscribers. The smallest displacement is also concerned. Having a list of listeners with their respective requests and their last location updates may solve this problem. When the location provider has a new location, it is thus possible to check if the new location has to be sent to each listener (according to the minimum interval and minimum displacement).

**Comment by msmollin** [comment]
@dmeignan Hmmmm, I guess I'm slightly confused by what you're asking for then. In your original request, you stated: 

> If my other component sends a request for location updates, the Mapbox component will not receive any more location updates

Which is why we suggested broadcast intents or a message bus system, as that would solve the problem. It doesn't address the accuracy problem or anything of that nature, but it would solve the problem of having multiple components be subscribed for location updates.

I'm also a little confused as to the use case you have here. You have multiple, disparate components of a single application requesting different accuracy levels at different update intervals? Like a foreground application and the other a background service? Maybe if we can understand the use case here a little better, it might be easier to come up with possible solutions?

**Comment by dmeignan** [comment]
Here are some details about the use case. I develop an app that displays a map and also computes and displays a bunch of stats related to the location.

I have two components that use location updates in my app:

- The first one is a [MapView](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java) from [Mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native). The map-view displays a map and it is possible to show the current location with a [UserLocationView](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/UserLocationView.java) layer. For my app, the user can switch-on or off this option to display the current location. The current location layer, through a [Mapbox-LocationServices](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationServices.java), submits requests to the LostApiClient. In the current implementation of the Mapbox SDK, parameters for requests are static values: 1000ms interval, 3 meters displacement. More annoying, the Mapbox-LocationServices class in Mapbox may disconnect the location client. Unfortunately, there is no methods in the Mapbox SDK to change the behavior of the Mapbox-LocationServices class.

- The second component that uses location updates is a Tracker that computes, records and displays some statistics about the location. For instance, the tracker can display the average speed (moving average value), the average distance from a target, and the average orientation (again moving average value). This tracker can also be switched-on or off by the user and it require more frequent location updates than the Mapbox component and always `PRIORITY_HIGH_ACCURACY`.

The problem is simple: When one of the two component is switched-on (the current-location layer or the tracker), its location request will overwrite the previous one with parameters that may be inadequate. Moreover, when the current-location layer or the tracker is disabled, a call to `removeLocationUpdates(LocationListener listener)` stops all location updates, even if another listener still requires updates, which is not the behavior I expected.

The problem is the same using broadcast intents. Only one of my two components has to setup the location updates. For instance, when the tracker is activated, it has to check whether the Mapbox component already sent a location updates request, and vice-versa. With this approach I have to change the code within the Mapbox SDK.

Having the LOST API managing multiple listeners would be great. As I mentioned in my previous message, with the Google [FusedLocationProviderApi](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderApi) you can register multiple listeners and you don’t have to take care of the "synchronization" of the requests.

**Comment by ecgreb** [comment]
@dmeignan I agree the ability to register multiple listeners should be added to maintain parity with Google Play services. And I can see why the workaround suggested is not going to work for your use case.

If we structure this correctly we may not even need to deal with "combining" the requests. We could  register multiple listeners with the [`LocationManager`](https://developer.android.com/reference/android/location/LocationManager.html) (one for each LOST listener) and let it handle the various criteria such as frequency, accuracy, displacement, etc.
