### ISSUE TITLE
Implement getLocationAvailability and onLocationAvailability

### ISSUE THREAD

**Issue by ecgreb** [mapzen/LOST#64]
Currently LOST provides no way to determine if a devices location services are enabled.

The Google Play API provides [LocationServices.FusedLocationApi.getLocationAvailability()](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderApi#getLocationAvailability(com.google.android.gms.common.api.GoogleApiClient)) and [LocationCallback.onLocationAvailability()](https://developers.google.com/android/reference/com/google/android/gms/location/LocationCallback#onLocationAvailability(com.google.android.gms.location.LocationAvailability)).

**Comment by christocracy** [comment]
You can set up a BroadcastReceiver to respond to provider changes in real-time

```
IntentFilter intentFilter = new IntentFilter(LocationManager.PROVIDERS_CHANGED_ACTION);
```

**Comment by Eksterminator** [comment]
I also got the same problem.
Once I put LocationCallback after 'implements' in the class I intend to use it it says 'Interface expected here'. I don't know how to sort it out as all rest of the code looks OK to work.
I've made everyting as usual while using LocationListener (I'm actually refactoring the code using LocationCallback and Looper instead of LocationListener),

I'm trying to register (?) the LocationCallback using the code:
    LocationServices.FusedLocationApi.requestLocationUpdates(mGoogleApiClient, mLocationRequest, this, null)
                    .setResultCallback(new ResultCallback<Status>() {
                        @Override
                        public void onResult(@NonNull Status status) {
                            if (status.isSuccess()) { /** LocationUpdates: ON */
                                mRequestingLocationUpdates = true;
                            }
                            else {/** Error, LocationUpdates fail to start */*/
                               ...
                        }


"Implement getLocationAvailability and SettingsApi" is not the greatest answer as SettingsApi approach  without LocationCallback requires polling... Perhaps some extra time event controlling location update time out.
I think that callback saying that something has changed in Location settings is the best, but how can I get rid of the 'Interface expected here' error ??
