### ISSUE TITLE
ActivityRecognition

### ISSUE THREAD

**Issue by christocracy** [mapzen/lost#66]
Is ActivityRecognitionAPI on the radar for this project?

**Comment by ecgreb** [comment]
Activity recognition is not currently on the lost roadmap.

Unfortunately since the Android framework relies on HAL native bindings for this functionality its not something we can tap into and would require developing our own (or finding another) open source native library to collect and process the sensor data needed for this type of service.

https://github.com/android/platform_frameworks_base/blob/master/core/java/android/hardware/location/ActivityRecognitionHardware.java

**Comment by ecgreb** [comment]
After taking another look at what would be required to support activity recognition it might be possible use the `ActivityRecognitionHardware` class (using Reflection since it is marked `@hide`) but this is still outside the current scope of the Lost project which is focused on implementing an open source version of the [LocationServices](https://developers.google.com/android/reference/com/google/android/gms/location/LocationServices) classes including the fused location provider, geofencing, and location settings APIs.

I could however conceive of a world where an open source version of the
[ActivityRecognitionApi](https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionApi) is implemented in a similar way possibly in its own project or as a new module in the Lost project.

**Comment by sarahlensing** [comment]
This is still out of scope. Closing for now, if we receive more demand for this api we can consider creating a new, open source version of the `ActivityRecognitionApi`.
